### PR TITLE
Fix #280 ~ don't clear payment form on cancel payment

### LINKED ISSUE #280: [Signup] Card info is lost if I click cancel on 3ds modal
**Steps to reproduce**
1. Go to signup
2. When asked for payment, enter 3ds card
3. in the 3ds modal, click cancel

**Video**
https://recordit.co/iWAsAsW55U

### PR DESCRIPTION
**Pull request by vincaslt**
Moved loading to when user is actually being created, so there is no weird redirect happening during payment.

This loading used to be on the whole function because PayPal didn't have a loading state, but now it does, so it's k.

### CODE REVIEW

File: src/app/containers/SignupContainer/SignupContainer.js [hunk 1]
```diff
@@ -201,11 +201,7 @@ const SignupContainer = ({ history, onLogin, stopRedirect }) => {
                         )}
 
                         {signupState === SignupState.Payment && (
-                            <PaymentStep
-                                model={model}
-                                paymentAmount={selectedPlan.price.total}
-                                onPay={(...rest) => withCreateLoading(handlePayment(...rest))}
-                            >
+                            <PaymentStep model={model} paymentAmount={selectedPlan.price.total} onPay={handlePayment}>
```
Comment (EpokK) [inline src/app/containers/SignupContainer/SignupContainer.js]: `onPay` returns `model, paymentParameters`?

Comment (vincaslt) [reply src/app/containers/SignupContainer/SignupContainer.js]: yes

Comment (vincaslt) [reply src/app/containers/SignupContainer/SignupContainer.js]: onPay is not the same one as on `Payment` component. Don't remember what problem exactly this solved, maybe it's not needed to return model there anymore, but it was less fragile this way.
